// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdvgWez6JlheIt-s34WMDotvH08MTkfQ0',
    appId: '1:121644975948:web:02272468ce9b1b108fb1e9',
    messagingSenderId: '121644975948',
    projectId: 'todolist-2e5a8',
    authDomain: 'todolist-2e5a8.firebaseapp.com',
    databaseURL: 'https://todolist-2e5a8-default-rtdb.firebaseio.com',
    storageBucket: 'todolist-2e5a8.appspot.com',
    measurementId: 'G-F1940YHHJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEgkoFP0DcXYRL_I9Plb0v484Kr4WYVJw',
    appId: '1:121644975948:android:4c7ec6b866949fc78fb1e9',
    messagingSenderId: '121644975948',
    projectId: 'todolist-2e5a8',
    databaseURL: 'https://todolist-2e5a8-default-rtdb.firebaseio.com',
    storageBucket: 'todolist-2e5a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMwD2adYGPkalyCoBn5HT2aG1xFX-NUpg',
    appId: '1:121644975948:ios:71b91196b6bfa94b8fb1e9',
    messagingSenderId: '121644975948',
    projectId: 'todolist-2e5a8',
    databaseURL: 'https://todolist-2e5a8-default-rtdb.firebaseio.com',
    storageBucket: 'todolist-2e5a8.appspot.com',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMwD2adYGPkalyCoBn5HT2aG1xFX-NUpg',
    appId: '1:121644975948:ios:786f07b29ca539558fb1e9',
    messagingSenderId: '121644975948',
    projectId: 'todolist-2e5a8',
    databaseURL: 'https://todolist-2e5a8-default-rtdb.firebaseio.com',
    storageBucket: 'todolist-2e5a8.appspot.com',
    iosBundleId: 'com.example.task2.RunnerTests',
  );
}
